### ISSUE TITLE
Duplicate Values Insertion When Parsing JSON with Badger DB

### ISSUE THREAD

**Issue by sanjayJ369** [sanjayJ369/LangApp#4]
When parsing a JSON file using Badger DB, we are encountering an issue where duplicate values are being inserted multiple times.

For example, in the exported file, the word "personal" appears repeatedly:

yo, informal "no", personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, personal pronoun, individual person as the object of own reflective consciousness, individual person as the object of own reflective

**Expected Behavior:**  
The JSON parsing should result in unique entries without duplicates.

**Actual Behavior:**  
The same value ("personal") is inserted multiple times, leading to data redundancy.

**Comment by wdipax** [comment]
@sanjayJ369 where can I get the JSON file with data to reproduce this problem?

**Comment by wdipax** [comment]
@sanjayJ369 is this issue solved?

**Comment by wdipax** [comment]
I believe this issue is solved.
